on: pull_request

name: Code Inspection
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection on code managed by Sage Goddess.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v2.1.0
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: "
          .github,
          .well-known"
        with:
          args: "WordPress-Extra,WordPress-Core,WordPress-Docs"